services:
  - type: web
    name: timon-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python timon.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
