services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python timon.py
    envVars:
      - key: PORT
        value: 10000